server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.217.241:3306/example?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: asd123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      pool-name: blah
  data:
    jpa:
      repositories:
        enabled: true
  thymeleaf:
    encoding: UTF-8
    content-type: text/html
    cache: false
  messages:
    basename: default
security:
  basic:
    enabled: false