castle:
  name: castle
  version: V3.0
  console-path: /console
  
logging:
  level:
    root: WARN

server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.176.40:3306/castle?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Stream123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      pool-name: blah
  data:
    jpa:
      repositories:
        enabled: true
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  messages:
    basename: default